import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Noto_Sans({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} dark bg-background antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
