import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import NavbarSection from "@/components/ui/custom/NavbarSection";
import GradiantSpot from "@/components/ui/custom/GradiantSpot";

const geistSans = Noto_Sans({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.className} h-screen bg-richblack-990 font-inter relative -z-40 overflow-x-hidden text-white`}
      >
        <Provider>
          <div className="relative h-full w-full overflow-hidden ">
            <NavbarSection />
            <div className="w-full h-full relative z-30 overflow-hidden">
              {children}
            </div>
          </div>
        </Provider>
        {/* gradiant spot */}
        <GradiantSpot classNames="absolute" />
      </body>
    </html>
  );
}
